### DISCUSSION TITLE
FAST-LIO2

### DISCUSSION THREAD

**Discussion by hogyun2** [DapengFeng/S3E#26] [General]
I appreciate for releasing an interesting paper.

I utilize a FAST-LIO2 algorithm in Dormitory datasets, but the odometry is diverged.
I think this is the extrinsic calibration issue, so can I obtain the extrinsic calibration parameters for the Dormitory dataset?
Now, I use the R:[[1,0,0], [0, 1, 0], [0, 0, 1]], T:[0, 0, 0] in DCL_FAST_LIO2.

**Comment by DapengFeng** [comment]
You can find the calibration parameter at https://huggingface.co/datasets/PengYu-Team/S3E/tree/main/S3Ev1/Calibration .

For example, the transformation matrix from the left camera to the imu of Alpha is written in `alpha.yaml`.
```yaml
# Transformation from left camera to imu
Tic: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.00671209, -0.00971447,  0.99993029,  0.14118513,
          -0.99993865, -0.00887635,  0.00662591,  0.1552482,
           0.00881136, -0.99991342, -0.00977345,  0.01917531,
           0.0,         0.0,         0.0,         1.0]
```
with the format:
```math
\begin{bmatrix}
R & T \\\
0  & 1
\end{bmatrix}.
```
