### DISCUSSION TITLE
The software used to get stereo rectificaiton parameters

### DISCUSSION THREAD

**Discussion by Mechazo11** [DapengFeng/S3E#30] [Q&A] [answered]
Hi @DapengFeng 

In `alpha.yaml`, `bob.yaml` and `carol.yaml` files, the stereo rectification data are provided in the following format

```yaml
#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
#--------------------------------------------------------------------------------------------
LEFT.height: 1024
LEFT.width: 1224
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.052628389768906, 0.100832689624109, 0.000395112517197, 0.000362060505238, 0.0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1172.771733138536,    0.0,            617.941545715258, 
             0.0,            1172.364005984343, 507.672727295385, 
             0.0,               0.0,              1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0,
          0.0, 1.0, 0.0,
          0.0, 0.0, 1.0]
LEFT.Rf:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 
          0.0, 1.0, 0.0, 
          0.0, 0.0, 1.0]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [1172.771733138536,    0.0,            617.941545715258, 0.0,  
             0.0,            1172.364005984343, 507.672727295385, 0.0,  
             0.0,               0.0,              1.0,            0.0]

RIGHT.height: 1024
RIGHT.width: 1224
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.052817970234810, 0.100073648217903, 0.000987319404990, 0.000078198322045, 0.0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1172.549603999100,    0.0,            617.477465353483, 
             0.0,            1173.241586185178, 516.335518983269, 
             0.0,               0.0,              1.0]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.999994846143267,   0.003159631643868,  -0.000569574209205,
         -0.003162491376236,   0.999982035625659,  -0.005091863534975,
          0.000553475564009,   0.005093638565765,   0.999986874169337]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [1172.549603999100,    0.0,              617.477465353483, -361.1747016345565 , 
             0.0,              1173.241586185178, 516.335518983269,   -5.2678945955122, 
             0.0,                 0.0,              1.0,              -1.5931129591554]
```
Which software / procedure was used to compute this data? Is it possible to get T_c1_c2 where c1 is the left camera frame and c2 is the right camera from directly from the provided data?
